### ISSUE TITLE
Bot makes no sound

### ISSUE THREAD

**Issue by smi3cht** [StudyLions/StudyLion#35]
Hi,

I have a issue, the bot doesn't make a sound / says anything anymore when the timer switches modes. I have tried giving giving the bot more rights. I even made a new channel but it does not work. The bot does join the voice channel when the timer has run out. I double checked all the settings the bot is not muted.  

Can you help me please? If you neem more info please let me know!

**Comment by Intery** [comment]
Hi!

Thanks for the report.
This is a known issue involving a race condition in the discord.py library we use. Unfortunately there is no known workaround for now aside from restarting the bot, however the issue should hopefully be fixed with the next major update (which upgrades the library version).

**Comment by smi3cht** [comment]
Thank you for the fast reply!
