### ISSUE TITLE
Economy balance updates are not logged

### ISSUE THREAD

**Issue by ShootingKing-AM** [StudyLions/StudyLion#6]
It seems the conins disbursed would be available in mod_logs but after server config, and some students studying and earning coins, its still not availbale in mod_logs and rather its empty.

Related images are below, yes Students studied AFTER the server was conf'ed with channels, etc.

![config-1](https://user-images.githubusercontent.com/4137788/141257646-4e81e4c5-3f05-4ad9-912b-326f9026fe53.png)
![config](https://user-images.githubusercontent.com/4137788/141257660-5478b83f-5d29-4c45-b717-d8d913b506c0.png)
![top](https://user-images.githubusercontent.com/4137788/141257679-008a58c5-85c8-4300-ba53-e7a6f1ef5c9f.png)
![log](https://user-images.githubusercontent.com/4137788/141257699-4369ece4-e451-4b4f-81d5-6a480a498e20.png)
![perms](https://user-images.githubusercontent.com/4137788/141257715-8719c932-5b27-4f4c-beb3-a2abd717e93a.png)

**Comment by Intery** [comment]
The `mod_log` is a ticket log channel intended as an enhanced audit log for moderation actions, not as an economy tracker. `event_log` would be more suitable for that, and most of the manual events which modify the user's balance are logged there.

However, I chose not to explicitly log all coins gained at this point, since there are potentially a lot of very spammy economy modifications. For example, each TODO task completed may give coins, and the accountability rewards also yield coins. The intention was to add a complete log for per-user economy data, accessible via command in future.

Further, the time tracking system is currently poll-based, per 5 seconds, and rewards fractional amounts accordingly, which is infeasible to log. However, we are in the process of migrating to a session based study tracker which will simplify this considerably, and we may optionally add the completed sessions to the event log (at least for smaller guilds).
