### ISSUE TITLE
untracked_channels is not visible in the config options

### ISSUE THREAD

**Issue by gokhanheim1** [StudyLions/StudyLion#69]
I want to configure StudyLion in my study server and I want to set the untracked channels, but I can't because the untracked_channels option is not present in the `/config voice_rewards` options:
<img width="527" alt="image" src="https://github.com/StudyLions/StudyLion/assets/159120630/8d2c859c-406f-479d-9d79-98775b39d26a">
![image](https://github.com/StudyLions/StudyLion/assets/159120630/860ae150-4816-4f66-9c2a-267709cd14bb)

**Comment by Intery** [comment]
@gokhanheim1 Indeed it is not possible to configure it by command, because Discord slash commands do not support lists of objects (i.e. a parameter can be a single channel, but not multiple channels).

Instead run the bare `/config voice_rewards` command (with no parameters), and use the UI elements which appear underneath the resulting settings widget to set the untracked channels.

(The setting widget may also be found by selecting 'Voice Tracker Configuration' from the menu underneath the `/dashboard` command output.)

Each setting group has its own settings widget with UI that enables setting the less discord-supported configuration settings. Long-form (paragraph type) settings can be set by clicking 'Edit' on those widgets.

**Comment by gokhanheim1** [comment]
perfect, thanks!
